DodgeNet/DodgeNet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movies.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DodgeNet/movies/urls.py
from django.urls import path

from .views import AllView, MovieDetailView, MoviesView, SeriesDetailView, SeriesView, AddMovieReview, ActorsView, AddSeriesReview

urlpatterns = [
    path("", AllView.as_view()),
    path("movies/<slug:slug>", MovieDetailView.as_view(), name="movie_detail"),
    path("series/<slug:slug>", SeriesDetailView.as_view(), name="series_detail"),
    path("movies/", MoviesView.as_view(), name="category_movies_detail"),
    path("series/", SeriesView.as_view(), name="category_series_detail"),
    path("review/movie/<int:pk>", AddMovieReview.as_view(), name="add_movie_review"),
    path("review/series/<int:pk>", AddSeriesReview.as_view(), name="add_series_review"),
    path("actors/", ActorsView.as_view(), name="actors_detail")
]

DodgeNet/movies/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Categories"""
    name = models.CharField("Categories", max_length=150)
    description = models.TextField("Description")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Actor(models.Model):
    """Actors"""
    name = models.CharField("Name", max_length=100)
    age = models.PositiveSmallIntegerField("Age", default=0)
    description = models.TextField("Description")
    image = models.ImageField("Image", upload_to="actors/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Actor and director"
        verbose_name_plural = "Actors and directors"


class Genre(models.Model):
    """Genres"""
    name = models.CharField("Name", max_length=100)
    description = models.TextField("Description")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Genre"
        verbose_name_plural = "Genres"


class Movie(models.Model):
    """Movies"""
    title = models.CharField("Title", max_length=150)
    tagline = models.CharField("Tagline", max_length=100, default="")
    description = models.TextField("Description")
    poster = models.ImageField("Poster", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Year of publication", default="")
    country = models.CharField("Country", max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name="Director", related_name="movie_director")
    actors = models.ManyToManyField(Actor, verbose_name="Actor", related_name="movie_actor")
    genres = models.ManyToManyField(Genre, verbose_name="Genres")
    budget = models.PositiveIntegerField("Budget", default=0, help_text="Amount of money in USD")
    fess_in_world = models.PositiveIntegerField("Fess in the world", default=0, help_text="Amount of money in USD")
    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Draft", default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})


class Series(models.Model):
    """Series"""
    title = models.CharField("Title", max_length=150)
    tagline = models.CharField("Tagline", max_length=100, default="")
    description = models.TextField("Description")
    poster = models.ImageField("Poster", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Year of publication", default="")
    country = models.CharField("Country", max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name="Director", related_name="series_director")
    actors = models.ManyToManyField(Actor, verbose_name="Actor", related_name="series_actor")
    genres = models.ManyToManyField(Genre, verbose_name="Genres")
    budget = models.PositiveIntegerField("Budget", default=0, help_text="Amount of money in USD")
    fess_in_world = models.PositiveIntegerField("Fess in the world", default=0, help_text="Amount of money in USD")
    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Draft", default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Series"
        verbose_name_plural = "Series"

    def get_absolute_url(self):
        return reverse("series_detail", kwargs={"slug": self.url})


class MovieShots(models.Model):
    """Movie Shots"""
    title = models.CharField("Title", max_length=100)
    description = models.TextField("Description")
    image = models.ImageField("Image", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Movie", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Movie shot"
        verbose_name_plural = "Movie shots"


class RatingStar(models.Model):
    """Rating in stars"""
    value = models.SmallIntegerField("Value", default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = "Rating star"
        verbose_name_plural = "Rating stars"


class Rating(models.Model):
    """Rating"""
    ip = models.CharField("IP Address", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="Star")
    movie = models.ForeignKey(Movie, on_delete=models.CharField, verbose_name="Movie")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Rating"
        verbose_name_plural = "Ratings"


class Review(models.Model):
    """Reviews"""
    name = models.CharField("Name", max_length=100)
    email = models.EmailField()
    text = models.TextField("Text", max_length=5000)
    parent = models.ForeignKey('self', verbose_name="Parents", on_delete=models.CASCADE, null=True)
    movie = models.ForeignKey(Movie, verbose_name="Movie", on_delete=models.CASCADE, null=True)
    series = models.ForeignKey(Series, verbose_name="Series", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

DodgeNet/movies/forms.py
from django import forms

from .models import *


class ReviewForm(forms.ModelForm):
    """ Review Form """

    class Meta:
        model = Review
        fields = ("name", "email", "text")

DodgeNet/movies/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .models import *
from .forms import *


class AllView(View):
    """All View"""

    def get(self, request):
        movies = Movie.objects.filter(draft=False)
        series = Series.objects.filter(draft=False)
        return render(request, "movies/main-pg.html", {'movies': movies, 'series': series})


class MovieDetailView(DetailView):
    """Movie Detail View"""

    model = Movie
    slug_field = "url"
    template_name = "movies/movie.html"


class SeriesDetailView(DetailView):
    """Series Detail View"""

    model = Series
    slug_field = "url"
    template_name = "movies/series.html"


class MoviesView(View):
    """Movies View"""

    def get(self, request):
        info = Movie.objects.filter(draft=False)
        cat = Movie.objects.first()
        return render(request, "movies/category.html", {'info': info, 'cat': cat})


class SeriesView(View):
    """Series View"""

    def get(self, request):
        info = Series.objects.filter(draft=False)
        cat = Series.objects.first()
        form = ReviewForm()
        return render(request, "movies/category.html", {'info': info, 'cat': cat, 'form': form})


class AddMovieReview(View):
    """ Add Comment """

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.save()
        return redirect(f"/movies/{movie.url}")


class AddSeriesReview(View):
    """ Add Comment """

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        series = Series.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.series = series
            form.save()
        return redirect(f"/series/{series.url}")


class ActorsView(ListView):
    """ Actors View """
    model = Actor
    template_name = "movies/actors.html"
    context_object_name = "actors"

DodgeNet/movies/templates/movies/actors.html
{% extends 'movies/base.html' %}

{% block title %}Actors{% endblock %}
{% block content %}

<div class="actors">
    <div class="container">
        <h1 class="actors_title">Actors:</h1>
        <ul class="actors_inner">
            {% for actor in actors %}
                <li class="actors_item">
                    <img src="{{actor.image.url}}" alt="Actor Image">
                    <div class="actors_content">
                      <h3>{{actor.name}}</h3>
                      <h6>{{actor.age}}</h6>
                      <div>{{actor.description}}</div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

DodgeNet/movies/templates/movies/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'movies/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,400;1,900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'movies/img/fav-icon/fav.svg' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<!-- SVG -->
<div class="svg" style="display: none;">
    <svg style="display: none;">
        <symbol id="arrow-right" viewBox="0 0 24 24">
            <g>
                <path fill-rule="evenodd" d="M.366 19.708c.405.39 1.06.39 1.464 0l8.563-8.264a1.95 1.95 0 0 0 0-2.827L1.768.292A1.063 1.063 0 0 0 .314.282a.976.976 0 0 0-.011 1.425l7.894 7.617a.975.975 0 0 1 0 1.414L.366 18.295a.974.974 0 0 0 0 1.413"></path>
            </g>
        </symbol>
    </svg>
    <svg style="display: none;">
        <symbol id="arrow-left" viewBox="0 0 24 24">
            <g>
                <path fill-rule="evenodd" d="M10.634.292a1.063 1.063 0 0 0-1.464 0L.607 8.556a1.95 1.95 0 0 0 0 2.827l8.625 8.325c.4.385 1.048.39 1.454.01a.975.975 0 0 0 .01-1.425l-7.893-7.617a.975.975 0 0 1 0-1.414l7.83-7.557a.974.974 0 0 0 0-1.413"></path>
            </g>
        </symbol>
    </svg>
</div>


<!-- All -->
    <div class="all">
        <header class="header" id="header">
            <div class="container">
                <div class="header_inner">
                    <a href="/" class="header_logo">Dodge<span>.Net</span></a>
                    <nav class="nav" id="nav">
                        <a href="/movies" class="nav_link">Movies</a>
                        <a href="/series" class="nav_link">Series</a>
                        <a href="/actors" class="nav_link">Actors</a>
                    </nav>
                    <!-- Mobile button -->
                    <button class="nav_toggle" id="nav-toggle" type="button">
                        <span class="nav_toggle__item">Menu</span>
                    </button>
                    <a href="/" style="opacity: 0" class="log_in_btn">Log In</a>
                </div>

            </div>
        </header>
        <main class="main">
            {% block content %}{% endblock %}
        </main>
    </div>

<!-- Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'movies/js/main.js'%}" type="text/javascript"></script>
</body>
</html>

DodgeNet/movies/templates/movies/category.html
{% extends 'movies/base.html' %}

{% block title %}{{cat.category}}{% endblock %}
{% block content %}

<div class="category">
    <div class="container">
        <h1 class="category_title">{{cat.category}}:</h1>
        <ul class="category_inner">
            {% for info in info %}
                <a href="{{info.get_absolute_url}}" class="category_item">
                    <img src="{{info.poster.url}}" alt="Category Image">
                </a>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

DodgeNet/movies/templates/movies/main-pg.html
{% extends 'movies/base.html' %}
{% block title %}DodgeNet{% endblock %}
{% block content %}
<!-- Movies -->
    <div class="main_content">
        <div class="container">
            <div class="main_title">Movies:</div>
            <div class="main_inner">
                {% for movie in movies %}
                    <a href="{{ movie.get_absolute_url }}" class="main_item">
                        <img src="{{movie.poster.url}}" alt="Movie Image">
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

<!-- Series -->
    <div class="main_content">
        <div class="container">
            <div class="main_title">Series:</div>
            <div class="main_inner">
                {% for serial in series %}
                    <a href="{{ serial.get_absolute_url }}" class="main_item">
                        <img src="{{serial.poster.url}}" alt="Movie Image">
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

DodgeNet/movies/templates/movies/movie.html
{% extends 'movies/base.html' %}
{% block title %}{{movie.title}}{% endblock %}
{% block content %}
<!-- Movies -->
    <div class="movie">
        <div class="container">
            <div class="movie_inner">
                <video src="/" controls></video>
                <div class="movie_item">
                    <div class="movie_item_left">
                        <img src="{{movie.poster.url}}" alt="Movie Image">
                    </div>
                    <div class="movie_item_right">
                        <h1 class="movie_title">{{movie.title}}</h1>
                        <h3>Date : <span>{{movie.year}}</span></h3>
                        <h3>Country : <span>{{movie.country}}</span></h3>
                        <h3>Directors : {% for director in movie.directors.all %}
                                            <span>{{director.name}} </span>
                                        {% endfor %}
                        </h3>
                        <h3>Actors : {% for actor in movie.actors.all %}
                                            <span>{{actor.name}} </span>
                                     {% endfor %}
                        </h3>
                        <h3>Description:</h3>
                        <div>{{movie.description}}</div>
                        <div class="rating">
                            <div class="imdb">IMDB 6.3</div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="movie_shots">
                {% if movie.movieshots_set.all %}
                    <h1 class="movie_shots_title">Shots from {{movie.title}}:</h1>

                    <ul class="movie_shots_inner">
                        {% for image in movie.movieshots_set.all%}
                            <li class="movie_shots_item">
                                <img src="{{image.image.url}}" alt="Shots from movie">
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            {% if movie.review_set.all %}
                <div class="comments">
                    <h1 class="comments_title">Comments:</h1>
                    <div class="comments_inner">
                        {% for review in movie.review_set.all %}
                            <div class="comments_item">
                                <h1>{{review.name}}:</h1>
                                <h3>{{review.email}}</h3>
                                <div>{{review.text}}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            <div class="comment">
                <div class="comment_inner">
                    <h1 class="comment_title">Add comment here:</h1>
                    <form action="{% url 'add_movie_review' movie.id %}" method="post" class="comment_form">
                        {% csrf_token %}
                        <label for="name" class="name">
                            <h1>Name:</h1>
                            <input type="text" name="name" id="name">
                        </label>
                        <label for="email" class="email">
                            <h1>Email:</h1>
                            <input type="email" name="email" id="email">
                        </label>
                        <label for="text" class="comment">
                            <h1>Comment:</h1>
                            <textarea name="text" id="text" cols="" rows=""></textarea>
                        </label>
                        <label for="submit_button">
                            <input type="submit" name="submit_button" id="submit_button" value="Send" class="submit_button">
                        </label>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

DodgeNet/movies/templates/movies/series.html
{% extends 'movies/base.html' %}
{% block title %}{{series.title}}{% endblock %}
{% block content %}
<!-- Movies -->
    <div class="movie">
        <div class="container">
            <div class="movie_inner">
                <video src="/" controls></video>
                <div class="movie_item">
                    <div class="movie_item_left">
                        <img src="{{series.poster.url}}" alt="Movie Image">
                    </div>
                    <div class="movie_item_right">
                        <h1 class="movie_title">{{series.title}}</h1>
                        <h3>Date : <span>{{series.year}}</span></h3>
                        <h3>Country : <span>{{series.country}}</span></h3>
                        <h3>Directors : {% for director in series.directors.all %}
                                            <span>{{director.name}} </span>
                                        {% endfor %}
                        </h3>
                        <h3>Actors : {% for actor in series.actors.all %}
                                            <span>{{actor.name}} </span>
                                     {% endfor %}
                        </h3>
                        <h3>Description:</h3>
                        <div>{{series.description}}</div>
                        <div class="rating">
                            <div class="imdb">IMDB 6.3</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="movie_shots">
                {% if movie.movieshots_set.all %}
                    <h1 class="movie_shots_title">Shots from {{movie.title}}:</h1>

                    <ul class="movie_shots_inner">
                        {% for image in movie.movieshots_set.all%}
                            <li class="movie_shots_item">
                                <img src="{{image.image.url}}" alt="Shots from movie">
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            {% if series.review_set.all %}
                <div class="comments">
                    <h1 class="comments_title">Comments:</h1>
                    <div class="comments_inner">
                        {% for review in series.review_set.all %}
                            <div class="comments_item">
                                <h1>{{review.name}}:</h1>
                                <h3>{{review.email}}</h3>
                                <div>{{review.text}}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            <div class="comment">
                <div class="comment_inner">
                    <h1 class="comment_title">Add comment here:</h1>
                    <form action="{% url 'add_series_review' series.id %}" method="post" class="comment_form">
                        {% csrf_token %}
                        <label for="name" class="name">
                            <h1>Name:</h1>
                            <input type="text" name="name" id="name">
                        </label>
                        <label for="email" class="email">
                            <h1>Email:</h1>
                            <input type="email" name="email" id="email">
                        </label>
                        <label for="text" class="comment">
                            <h1>Comment:</h1>
                            <textarea name="text" id="text" cols="" rows=""></textarea>
                        </label>
                        <label for="submit_button">
                            <input type="submit" name="submit_button" id="submit_button" value="Send" class="submit_button">
                        </label>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}